# Generated by Django 4.2.23 on 2025-08-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('dob', models.DateField(verbose_name='Дата рождения')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Оплата')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Долг за услуги')),
                ('notes', models.TextField(blank=True, default=None, verbose_name='Заметки')),
                ('date_pay', models.DateField(verbose_name='Дата оплаты')),
                ('date_end_pay', models.DateField(verbose_name='Дата последнего платежа')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.provider', verbose_name='Провайдер')),
                ('type_of_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.typeofpayment', verbose_name='Тип оплаты')),
            ],
        ),
    ]
