# Generated by Django 4.2.23 on 2025-08-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeofpayment',
            old_name='firstname',
            new_name='name',
        ),
    ]
