# Generated by Django 4.2.23 on 2025-08-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_firstname_typeofpayment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Заметки'),
        ),
    ]
